version: 0.2

phases:
  install:
    commands:
      - choco install -y cmake
  pre_build:
    commands:
      - mkdir build; cd build
      - '&"C:\Program Files\CMake\bin\cmake.exe" ..'
  build:
    commands:
      - '&"C:\Program Files\CMake\bin\cmake.exe" --build . --config RelWithDebInfo'
      - ./RelWithDebInfo/app.exe
artifacts:
  files:
    - 'build/RelWithDebInfo/**/*'
  discard-paths: yes
